### ISSUE TITLE
Native ARM64 Docker Image

### ISSUE THREAD

**Issue by matteoveglia** [cgwire/kitsu-docker#32]
**Context**
Studio name: Undisclosed
Kitsu version: Latest
Production type: VFX

**Describe the bug**
There's no arm64 build of Kitsu on DockerHub, would be great if part of the build system included building for arm64 so I don't need to build manually on every release.
ARM machines are getting increasingly performant and I'm able to run an 80-core 512GB VPC in Oracle Cloud for a 1/3 to 1/4 cost as an AMD/Intel (respectively) counterpart.
https://www.oracle.com/ca-en/cloud/compute/arm/

Screenshots
![image](https://user-images.githubusercontent.com/1258632/209020381-295de58e-e4e3-4a47-9d70-8e0ce7b379a4.png)

**Comment by nledez** [comment]
Hello, a few months ago I set up arm64 support but I forgot to tell you.
As a reminder, this image is only there for Kitsu testing purposes. It is not recommended to use it in production.

![image](https://github.com/user-attachments/assets/44588027-ff28-4a7c-9003-915764d0edb1)
