### ISSUE TITLE
postgresql entered FATAL state, too many start retries too quickly

### ISSUE THREAD

**Issue by RyougiShiki-214** [cgwire/kitsu-docker#34]
`Docker version 25.0.3, build 4debf41`
I found that I cannot login through Kitsu's default username and password, so I checked the console and got those error:

`root@MyServer:~# docker run --init -ti --rm -p 80:80 -p 1080:1080 --name cgwire cgwire/cgwire`
`[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.`
`Zombie processes will not be re-parented to Tini, so zombie reaping won't work.`
`To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.`
`Running Zou...`
`2024-04-05 03:42:19,035 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.`
`2024-04-05 03:42:19,039 INFO RPC interface 'supervisor' initialized`
`2024-04-05 03:42:19,039 CRIT Server 'unix_http_server' running without any HTTP authentication checking`
`2024-04-05 03:42:19,039 INFO supervisord started with pid 12`
`2024-04-05 03:42:20,041 INFO spawned: 'gunicorn' with pid 15`
`2024-04-05 03:42:20,042 INFO spawned: 'gunicorn-events' with pid 16`
`2024-04-05 03:42:20,059 INFO spawned: 'redis' with pid 17`
`2024-04-05 03:42:20,060 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES`
`2024-04-05 03:42:20,063 INFO spawned: 'nginx' with pid 18`
`2024-04-05 03:42:21,082 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2024-04-05 03:42:21,082 INFO success: gunicorn-events entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2024-04-05 03:42:21,082 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2024-04-05 03:42:21,083 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES`
`2024-04-05 03:42:21,084 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)`
`2024-04-05 03:42:23,086 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES`
`2024-04-05 03:42:26,087 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES`
`2024-04-05 03:42:26,087 INFO gave up: postgresql entered FATAL state, too many start retries too quickly`
![image](https://github.com/cgwire/kitsu-docker/assets/53418317/b1ae7d7f-09b4-49fa-800e-b7f374546b53)

**Comment by frankrousseau** [comment]
Thank you for reporting, we will check the image again.

**Comment by RyougiShiki-214** [comment]
> Thank you for reporting, we will check the image again.

Today I tried to build the docker image from this repo instead of pull image from docker hub, and I got it running well. 
For comparison, I tried the image cgwire/cgwire from Docker Hub, and the error appeared again.
It seems that something went wrong in the [Docker Hub image](https://hub.docker.com/r/cgwire/cgwire), and the error still exist in Docker Hub image today.

**Comment by frankrousseau** [comment]
I was able to set up the image on my computer. It may be related to your installation.

**Comment by stephanebertrand** [comment]
I have the same issue with the image on Docker Image: PostgreSQL encounters a problem at startup until the message:
gave up: postgresql entered FATAL state, too many start retries too quickly.

I am going to test by building the image from the repository.

**Comment by nledez** [comment]
Hi @RyougiShiki-214 can you tell me if you still have this error?
Thanks.

**Comment by RyougiShiki-214** [comment]
> Hi @RyougiShiki-214 can you tell me if you still have this error? Thanks.

![image](https://github.com/user-attachments/assets/deb7847f-df11-40cc-9fb6-8b9c0229abe0)

I tried just now, and it seems that this problem had been solved
